# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'welcome123'
      MYSQL_DATABASE: 'Venom'
    command: --default-authentication-plugin=mysql_native_password
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    build: .
    command: flask run --host 0.0.0.0 -p 5000
    ports:
      - "8000:5000"
    depends_on:
      - "db"